//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNER
    {
        public int ID { get; set; }
        public string HinhBN { get; set; }
        public string Noidung { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
