//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public int ID { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> CMND { get; set; }
        public string GioiTinh { get; set; }
        public string NgaySinh { get; set; }
        public string NgayLap { get; set; }
        public string DiaChi { get; set; }
        public string UserName { get; set; }
    }
}
