//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
