//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string NamSX { get; set; }
        public Nullable<int> TheLoai { get; set; }
        public Nullable<int> NCC { get; set; }
        public Nullable<double> Gia { get; set; }
        public string HinhSP { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<System.DateTime> Hot { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
