//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int ID { get; set; }
        public string LoaiTinTuc { get; set; }
        public string TenTinTuc { get; set; }
        public string NoiDung { get; set; }
        public string Hinh { get; set; }
    }
}
